#!/usr/bin/env python3
"""
Convert ROS2 .srv files to Protocol Buffers .proto files

This script converts all .msg, .srv, .action files in vyra_base/interfaces/
to equivalent .proto files in vyra_base/interfaces/proto/
"""

import re
from pathlib import Path

def parse_iface_file(iface_path: Path) -> dict:
    """Parse a ROS2 .srv file and extract request/response fields."""
    content = iface_path.read_text()
    
    # Split by ---
    parts = content.split('---')
    
    request_fields = []
    response_fields = []
    
    # Parse request (part before ---)
    if len(parts) > 0:
        for line in parts[0].strip().split('\n'):
            line = line.split('#')[0].strip()  # Remove comments
            if not line or line.startswith('#'):
                continue
            
            # Parse: type field_name [default_value]
            match = re.match(r'(\S+)\s+(\S+)', line)
            if match:
                field_type = match.group(1)
                field_name = match.group(2)
                request_fields.append((field_type, field_name))
    
    # Parse response (part after ---)
    if len(parts) > 1:
        for line in parts[1].strip().split('\n'):
            line = line.split('#')[0].strip()  # Remove comments
            if not line or line.startswith('#'):
                continue
            
            match = re.match(r'(\S+)\s+(\S+)', line)
            if match:
                field_type = match.group(1)
                field_name = match.group(2)
                response_fields.append((field_type, field_name))
    
    return {
        'request': request_fields,
        'response': response_fields
    }


def ros_type_to_proto(ros_type: str) -> str:
    """Convert ROS2 type to Protocol Buffers type."""
    type_map = {
        'bool': 'bool',
        'int8': 'int32',
        'uint8': 'uint32',
        'int16': 'int32',
        'uint16': 'uint32',
        'int32': 'int32',
        'uint32': 'uint32',
        'int64': 'int64',
        'uint64': 'uint64',
        'float32': 'float',
        'float64': 'double',
        'string': 'string',
        'time': 'int64',  # Unix timestamp
        'duration': 'int64',
    }
    
    # Handle arrays
    if '[]' in ros_type:
        base_type = ros_type.replace('[]', '').strip()
        proto_type = type_map.get(base_type, 'string')
        return f'repeated {proto_type}'
    
    return type_map.get(ros_type, 'string')


def generate_proto_file(srv_name: str, fields: dict, package_name: str = "vyra_base") -> str:
    """Generate Protocol Buffers .proto content from parsed fields."""
    
    proto_content = f'''// Generated by Vyra Copy Script
syntax = "proto3";

package {package_name};

// Auto-generated from {srv_name}.srv
// Request message for {srv_name} service
message {srv_name}Request {{
'''
    
    # Add request fields
    field_num = 1
    for field_type, field_name in fields['request']:
        proto_type = ros_type_to_proto(field_type)
        proto_content += f'    {proto_type} {field_name} = {field_num};\n'
        field_num += 1
    
    if not fields['request']:
        proto_content += '    // Empty request\n'
    
    proto_content += f'''}}

// Response message for {srv_name} service
message {srv_name}Response {{
'''
    
    # Add response fields
    field_num = 1
    for field_type, field_name in fields['response']:
        proto_type = ros_type_to_proto(field_type)
        proto_content += f'    {proto_type} {field_name} = {field_num};\n'
        field_num += 1
    
    if not fields['response']:
        proto_content += '    // Empty response\n'
    
    proto_content += f'''}}

// Service definition
service {srv_name}Service {{
    rpc {srv_name} ({srv_name}Request) returns ({srv_name}Response);
}}
'''
    
    return proto_content


def main():
    # Paths
    base_dir = Path(__file__).parent.parent
    publisher_dir = base_dir / "src" / "vyra_base" / "interfaces" / "publisher"
    service_dir = base_dir / "src" / "vyra_base" / "interfaces" / "service"
    action_dir = base_dir / "src" / "vyra_base" / "interfaces" / "action"
    proto_dir = base_dir / "src" / "vyra_base" / "interfaces" / "proto"
    
    # Create proto directory
    proto_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"Converting .srv files from {service_dir} to {proto_dir}")
    
    for type, dir in [(".msg",publisher_dir), (".srv", service_dir), (".action", action_dir)]:
        for iface_file in dir.glob(f"*{type}"):
            iface_name = iface_file.stem
            
            print(f"Converting {iface_file.name} → {iface_name}.proto")
            
            # Parse .srv file
            fields = parse_iface_file(iface_file)
            
            # Generate .proto file
            proto_content = generate_proto_file(iface_name, fields)
            
            # Write .proto file
            proto_path = proto_dir / f"{iface_name}.proto"
            proto_path.write_text(proto_content)
            
            print(f"  ✅ Created {proto_path.name}")
    
    print(f"\n✅ Conversion complete! Created {len(list(proto_dir.glob('*.proto')))} .proto files")


if __name__ == "__main__":
    main()
